spring:
  application:
    name: spring-batch
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_batch
    username: kdkim
    password: 3764
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        hibernate-dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
  batch:
    job:
      name: ${job.name:None}
      enabled: true
    jdbc:
      initialize-schema: always
